### ISSUE TITLE
Loop detected for double parents

### ISSUE THREAD

**Issue by twonky4** [daveagp/family-tree#2]
Is it somehow possible to show this relationship?
```
ParentGirl1 + ParentBoy1
 c: Girl1, Girl2
ParentGirl2 + ParentBoy2
 c: Boy1, Boy2
Girl1 + Boy1
Girl2 + Boy2
```

It says to me "loop detected".

**Comment by daveagp** [comment]
This isn't currently supported as it generates a cycle in the family tree:
PG1 > G1 > child of G1 B1 > B1 > PG2 > B2 > child of G2 B2 > G2 > PG1

The layout algorithm is the culprit in particular. It would need some totally new logic to be able to come up with a strategy to show this

**Comment by daveagp** [comment]
Sorry hit the wrong button - open if there's suggestions on adding layout functionality

**Comment by twonky4** [comment]
okay. The answer is enought for me. I will put the relationship in the `note` section.
