### ISSUE TITLE
multiple marriages and descent

### ISSUE THREAD

**Issue by flint002** [daveagp/family-tree#3]
hi my mother got married twice 
and my grandfather got married four times
how i put in family.txt

mother +  father 1 +  father 2 

mother + father1
c : c1, c2
mother + father2
c : c3, c4

grandfather + grandmother 1 + grandmother 2+ grandmother 3+ grandmother 4

grandfather + grandmother 1
c : cc1,  cc2
grandfather + grandmother 2
c : cc3,  cc4
grandfather + grandmother 3
c : cc5,  cc6
grandfather + grandmother 4
c : cc7,  cc8

i like your code its simple

**Comment by daveagp** [comment]
The first thing - two spouses - is supported, but the simple code uses the text sequence as a hint for the visual layout. Consequently you need father1 on one side and father2 on the other side

**father1 + mother**
c : c1, c2
mother + father2
c : c3, c4

The code doesn't support more than 2 spouses for someone. There would be a sizeable chunk of work to figure out how to do this, probably touching and modifying quite a lot of the existing codebase.

If you don't want to change the codebase, it'll be a little bit tricky,
- having some spouses as standalone individuals won't work as the whole tree needs to be connected
- cloning grandfather won't work for the same reason... unless perhaps you make the clones siblings of the grandfather (you'll have to give them all parents)
- if 2 or fewer of the 4 partnerships resulted in children, a hacky way to store the data is just mention all the other spouses in grandfathers' notes, though of course those spouses won't visually show up in the tree

**Comment by flint002** [comment]
this working perfect

> father1 + mother
c : c1, c2
mother + father2
c : c3, c4

thankyou i will try your suggestion
